name: Frontend CI

on:
  pull_request:
    branches: [ main ]
    paths: 
      - 'frontend/**'
  workflow_dispatch:  # This is for allowing the manual trigger (in addition to pull request)

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 
        uses: actions/setup-node@v3
        with:
          node-version: '18.14' # comes from .nvmrc
      - name: Install dependencies
        run: npm ci
      - name: Run Linter
        run: npm run lint

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 
        uses: actions/setup-node@v3
        with:
          node-version: '18.14' # comes from .nvmrc
      - name: Install dependencies
        run: npm ci
      - name: Run Tests
        run: npm test

  build:
    runs-on: ubuntu-latest
    needs: [lint, test]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 
        uses: actions/setup-node@v3
        with:
          node-version: '18.14' # comes from .nvmrc
      - name: Install dependencies
        run: npm ci
      - name: Build Frontend
        run: npm run build