name: Backend CI

on:
  pull_request:
    branches: [ main ]
    paths: 
      - 'backend/**'
  workflow_dispatch:  # This is for allowing the manual trigger (in addition to pull request)

jobs:
  check_shell_availability:
    runs-on: ubuntu-latest
    steps:
    - name: Check out source repository
      uses: actions/checkout@v4
    - name: Check if /usr/bin/bash exists
      run: |
        pwd
        ls .
        ls starter
        ls starter/backend
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out source repository
        uses: actions/checkout@v4
      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        working-directory: starter/backend
        run: |
          python -m pip install --upgrade pip
          pip install pipenv
          pipenv lock
          pipenv install --system --deploy

      - name: Run lint
        working-directory: starter/backend
        run: |
          pip install flake8
          pipenv run lint

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out source repository
        uses: actions/checkout@v4
      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        working-directory: starter/backend
        run: |
          python -m pip install --upgrade pip
          pip install pipenv
          pipenv install --system --deploy

      - name: Run test
        working-directory: starter/backend
        run: pytest

  build:
    runs-on: ubuntu-latest
    needs: [lint, test]
    steps:
      - name: Check out source repository
        uses: actions/checkout@v4
      - name: Build Image
        working-directory: starter/backend
        run: docker build -t backend .  # Assuming you build a Docker image
