name: Backend CI

on:
  pull_request:
    branches: [ main ]
    paths: 
      - 'backend/**'
  workflow_dispatch:  # This is for allowing the manual trigger (in addition to pull request)

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        working-directory: starter/backend
        run: |
          python -m pip install --upgrade pip
          pip install pipenv
          pipenv install --system --deploy

      - name: Lint with flake8
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        working-directory: starter/backend
        run: |
          python -m pip install --upgrade pip
          pip install pipenv
          pipenv install --system --deploy

      - name: Run test
        working-directory: starter/backend
        run: pytest

  build:
    runs-on: ubuntu-latest
    needs: [lint, test]
    steps:
      - name: Build Image
        working-directory: starter/backend
        run: docker build -t backend .  # Assuming you build a Docker image
