name: Frontend CD

on:
  push:
    branches: [ main ]
    paths: 
      - 'frontend/**'
  workflow_dispatch:  # This is for allowing the manual trigger (in addition to push)

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        working-directory: starter/frontend
        uses: actions/setup-node@v4
        with:
          node-version: '18.14.2'
      - name: Run test
        run: |
          npm install
          npm test

  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        working-directory: starter/frontend
        uses: actions/setup-node@v4
        with:
          node-version: '18.14.2'
      - name: Run build
        run: echo '..building the image..'

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        working-directory: starter/frontend
        uses: actions/setup-node@v4
        with:
          node-version: '18.14.2'
      - name: Deploy
        run: echo '..deploying..'