name: Frontend CD

on:
  push:
    branches: [ main ]
    paths: 
      - 'frontend/**'
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 
        uses: actions/setup-node@v4
        with:
          node-version: '18.14.2' # comes from .nvmrc
      - name: Clean npm cache and remove node_modules
        working-directory: starter/frontend
        run: |
          npm cache clean --force
          rm -rf node_modules
      - name: Install dependencies
        working-directory: starter/frontend
        run: npm install
      - name: Run Linter
        working-directory: starter/frontend
        run: npm run lint -- --fix

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 
        uses: actions/setup-node@v4
        with:
          node-version: '18.14.2' # comes from .nvmrc
      - name: Clean npm cache and remove node_modules
        working-directory: starter/frontend
        run: |
          npm cache clean --force
          rm -rf node_modules
      - name: Install dependencies
        working-directory: starter/frontend
        run: npm install
      - name: Run Tests
        working-directory: starter/frontend
        run: npm test

  build:
    runs-on: ubuntu-latest
    needs: [lint, test]
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18.14.2'
      - name: Run build
        working-directory: starter/frontend
        run: |
          docker build -t frontend:${GITHUB_SHA} . 
          echo 'image built'

  deploy:
    runs-on: ubuntu-latest
    environment: Production
    needs: build
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18.14.2'
      - name: Authenticate to AWS
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Push image to ECR
        run: echo "..pushing image to ECR.."

      - name: Deploy to EKS
        working-directory: starter/frontend
        run: echo '..deploying to EKS..'